# Generated by Django 6.0.3 on 2026-04-16 07:36

from django.db import migrations, models


def migrate_products_table(apps, schema_editor):
    vendor = schema_editor.connection.vendor

    if vendor == "mysql":
        schema_editor.execute("DROP TABLE IF EXISTS `prouct_products_new`")
        schema_editor.execute(
            """
            CREATE TABLE `prouct_products_new` (
                `product_id` integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
                `name` varchar(100) NOT NULL,
                `price` double precision NOT NULL,
                `stock` integer NOT NULL,
                `description` longtext NULL,
                `image_url` longtext NOT NULL
            )
            """
        )
        schema_editor.execute(
            """
            INSERT INTO `prouct_products_new` (`name`, `price`, `stock`, `description`, `image_url`)
            SELECT `name`, `price`, `stock`, `description`, '[]'
            FROM `prouct_products`
            """
        )
        schema_editor.execute(
            """
            RENAME TABLE
                `prouct_products` TO `prouct_products_old`,
                `prouct_products_new` TO `prouct_products`
            """
        )
        schema_editor.execute("DROP TABLE `prouct_products_old`")
        return

    if vendor == "sqlite":
        schema_editor.execute('DROP TABLE IF EXISTS "prouct_products_new"')
        schema_editor.execute(
            """
            CREATE TABLE "prouct_products_new" (
                "product_id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "name" varchar(100) NOT NULL,
                "price" real NOT NULL,
                "stock" integer NOT NULL,
                "description" text NULL,
                "image_url" text NOT NULL DEFAULT '[]'
            )
            """
        )
        schema_editor.execute(
            """
            INSERT INTO "prouct_products_new" ("name", "price", "stock", "description", "image_url")
            SELECT "name", "price", "stock", "description", '[]'
            FROM "prouct_products"
            """
        )
        schema_editor.execute('DROP TABLE "prouct_products"')
        schema_editor.execute(
            'ALTER TABLE "prouct_products_new" RENAME TO "prouct_products"'
        )
        return

    raise NotImplementedError(f"Unsupported database vendor: {vendor}")


class Migration(migrations.Migration):

    dependencies = [
        ('prouct', '0002_remove_products_image_url_remove_products_product_id_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(migrate_products_table, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='products',
                    name='id',
                ),
                migrations.RemoveField(
                    model_name='products',
                    name='image',
                ),
                migrations.AddField(
                    model_name='products',
                    name='image_url',
                    field=models.JSONField(blank=True, default=list),
                ),
                migrations.AddField(
                    model_name='products',
                    name='product_id',
                    field=models.AutoField(primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
